### PR TITLE
Set things up for being able to version EventManager API

### PR DESCRIPTION
**Pull request by garronej**
Hello everyone, 

I think I came up with an optimal solution for versioning the `EventManager` API.

image

[text version](https://gist.github.com/garronej/84dddc6dad77d9fd0ce5608148bc59c4)

What do you guys think?  

Next up for me is to improve at least a little bit the `EventEmitterish` API, `on` and `emit` only are not enough. There is at least need for `detach()` and `once()` am I right? 

Cheers

### CODE REVIEW

**Comment by filfat** [comment]
This looks great! Thanks for your amazing work @garronej !

**Comment by garronej** [comment]
@filfat Thank you, it's my pleasure 😊   
I am not familiar enough with the project to tell but should the plugin maker be allowed to emit events on the  `EventManager` or should they just be able to listen?  
Because if they are not supposed to post we should not expose the `emit()` method.

Another point, I advise you against using `export default`, I know the JavaScript folks use it a lot but in a TypeScript project, it is better to just export the token like `export const foo ={}` and import with `import {foo } from "./foo";` much easier to maintain and you get the autocompletion for what if importable from a module.

**Comment by filfat** [comment]
@garronej Plugins should be able to also emit events, but built in but also custom that they define (for example you might be building and RPG plugin and want other plugins to subscribe to a playerLevelUp event).

Personally I prefer using `export default` for the class (or function) matching the file name and a normal export for types, etc that might also be included in the file.

**Comment by garronej** [comment]
> Plugins should be able to also emit events, but built in but also custom that they define (for example you might be building and RPG plugin and want other plugins to subscribe to a playerLevelUp event).

Ok I see! We have to support custom event then. If we just add `[string, any]` to the `EventTypes` union type we will completely loose the type inference and we dont want that. I will make a PR.

So you confirm that plugin maker should be allowed to emit each of those events: `raknetConnect`, `raknetDisconnect`, `raknetEncapsulatedPacket`, `chat`, `playerConnect`,  `playerDisconnect`, `playerSpawn`, `playerDespawn` and `playerMove`? None of them should be protected?

**Pull request merged**
