### PR TITLE
Add support for modern EMCAScript

### PR DESCRIPTION
**Pull request by filfat**
This is a draft PR to gather general feedback regarding the use of typescript, babel and es2020.

While the current bootstrapping processes is a bit slower (due to using babel-register) my plan is to eventually migrate to building everything into a bundle pre-runtime which would hypothetically allow for faster speeds.

### CODE REVIEW

**Comment by nougator** [comment]
What is EMCAScript?

**Comment by TheArmagan** [comment]
> What is EMCAScript?

original name of javascript

**Comment by nougator** [comment]
But why adding support support for this?

**Comment by filfat** [comment]
> But why adding support support for this?

Newer language features (usually) makes the code a lot simpler and more readable. For example remember when async/await wasn’t part of the current spec and how simple it makes everything now. This will also be a basis for bundler support so that we’ll be able to compile everything into a nice bundle (with dependencies included) to be distributed to the end-user.

**Comment by nougator** [comment]
But it's a **server side** app node.js that doesn't really this kind of thing, it will be good if it's a deno app

**Comment by DelxHQ** [comment]
🙄

**Comment by filfat** [comment]
> But it's a **server side** app node.js that doesn't really this kind of thing, it will be good if it's a deno app

Being a server side app doesn't change the usefulness of being able to use modern ES features nor does it mitigate the improvements in both UX and bootstrapping time for JIT compiler from bundling.

Also, the end-user presumably doesn't have any knowledge about about the node/npm ecosystem and would probably prefer  just downloading and running an executable. While bundling isn't strictly necessary for that it makes it a whole lot easier (on top of the aforementioned improvements) but that again isn't the primary purpose of this specific PR thus it doesn't make sense to continue discussion regarding that. This is again about the usage of modern ES features and perhaps typescript.

**Comment by nougator** [comment]
Seems ok then

**Pull request closed without merging**
