### PR TITLE
Use a different Evt instance for each event type

### PR DESCRIPTION
**Pull request by garronej**
See [PR#152](https://github.com/JSPrismarine/JSPrismarine/pull/152)

### CODE REVIEW

**Comment by garronej** [comment]
I close this PR in favor of [PR#154](https://github.com/JSPrismarine/JSPrismarine/pull/154)

**Comment by filfat** [comment]
To expand on what @bavfalcon9 said in #152, the idea is to keep the plugin API versioned.
This is not entirely accomplished with the event system yet since the internal classes for player etc are exposed and they might change. The proper way to handle this is probably to set up an event forwarder in https://github.com/JSPrismarine/JSPrismarine/blob/master/src/plugin/api/versions/1.0/EventManager.ts by creating a new instance of evt which we post modified events to with the pluginAPI specific classes when the internal event system fires.

I would personally also prefer to have a specific evt instance and/or function for every event, but after a discussion on our discord the current community decided that the `.on('id', callback)` is the preferred approach.

**Comment by garronej** [comment]
> To expand on what @Bavfalcon9 said in #152, the idea is to keep the plugin API versioned.
> This is not entirely accomplished with the event system yet since the internal classes for player etc are exposed and they might change. The proper way to handle this is probably to set up an event forwarder in https://github.com/JSPrismarine/JSPrismarine/blob/master/src/plugin/api/versions/1.0/EventManager.ts by creating a new instance of evt which we post modified events to with the pluginAPI specific classes when the internal event system fires.
> 
> I would personally also prefer to have a specific evt instance and/or function for every event, but after a discussion on our discord the current community decided that the `.on('id', callback)` is the preferred approach.

Ok I will think about what would be the ideal solution taking your constraints in consideration.
... But as for right now I have to focus on the code I am paid to write 😅

Cheers

**Comment by garronej** [comment]
@filfat I think I have figured out a good solution for what you try to achieve. But first les me help you remove the unnecessary asynchronous code. 😊

**Pull request closed without merging**
